sudo: true
language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'

install:
  - sudo add-apt-repository ppa:ondrej/php -y
  - sudo apt-get update -yy
  - sudo apt-get install -y php-bcmath

before_script:
  - composer install -o -q

jobs:
  include:
    - stage: build
      install:
        - composer require edgedesign/phpqa --update-no-dev --no-progress -q
      script:
        - ./vendor/bin/phpqa --analyzedDirs src --output cli --tools phpcs:0,phpmd,phpcpd:0,phpmetrics:0,phploc,pdepend
    - stage: test
      script:
        - ./vendor/bin/phpunit -c phpunit.xml.dist

cache:
  directories:
  - $HOME/.composer/cache/files
